notifications:
  slack: sh8email:qNoXMbOfcNQbYok7JqY1ptTn

language: python
python:
  - "3.4"
  - "3.5"

services:
  - postgresql

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt


dist: trusty
sudo: required
addons:
  firefox: "47.0.1"

before_script:
  # Set up postgresql database engine.
  - psql -c "CREATE USER sh8email WITH PASSWORD 'password';" -U postgres
  - psql -c "CREATE DATABASE sh8email;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE sh8email to sh8email;" -U postgres
  - psql -c "ALTER USER sh8email CREATEDB;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate -v 3
  - python manage.py collectstatic --noinput
  - python manage.py runrecv &
  - python manage.py runbatch &
  - python manage.py runserver &


script:
  - python manage.py test sh8core -v 3
  - python manage.py test web -v 3
  - python manage.py test functional_tests -v 3
  - python manage.py test recvmail -v 3

env:
  global:
    - BUILD_ON_TRAVIS=true


