language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies

notifications:
  slack: sh8email:qNoXMbOfcNQbYok7JqY1ptTn

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python -m recvmail.recv_server &


dist: trusty
sudo: required
addons:
  firefox: "48.0"

before_script:
  - python manage.py makemigrations 
  - python manage.py migrate -v 3
  - python manage.py collectstatic --noinput
  - python manage.py runrecv
  - python manage.py runbatch


script:
  - python manage.py test sh8core -v 3
  - python manage.py test web -v 3
  - python manage.py test functional_tests -v 3
  - python manage.py test recvmail -v 3

env:
  global:
    - BUILD_ON_TRAVIS=true


